# deploy/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: channelog
  namespace: channelog
  labels:
    app: channelog
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: channelog
  template:
    metadata:
      labels:
        app: channelog
    spec:
      restartPolicy: Always
      # mount the host's /dev/ppp
      volumes:
      - name: cert
        secret:
          secretName: channelog-certs
      - name: dev-ppp
        hostPath:
          path: /dev/ppp
          type: CharDevice
      - name: prompts
        configMap:
          name: channelog-prompts

      containers:
      - name: channelog
        image: nirnaye2e/channelog:v1
        imagePullPolicy: Always
        args:
          - --tlsCertFile=/certs/tls.crt
          - --tlsKeyFile=/certs/tls.key
        securityContext:
          privileged: true
        volumeMounts:
        - name: cert
          mountPath: /certs
          readOnly: true
        - name: dev-ppp
          mountPath: /dev/ppp
        - name: prompts
          mountPath: /prompts
          readOnly: true
        envFrom:
        - secretRef:
            name: channelog-certs
        env:
        - name: SYSTEM_PROMPT
          valueFrom:
            configMapKeyRef:
              name: channelog-prompts
              key: system-prompt
        - name: USER_MESSAGE_TEMPLATE
          valueFrom:
            configMapKeyRef:
              name: channelog-prompts
              key: user-message-template
        ports:
        - containerPort: 8443
          name: https
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
            ephemeral-storage: "2Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
            ephemeral-storage: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: channelog-service
  namespace: channelog
spec:
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app: channelog
