apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-event-channelog
webhooks:
  # Node Events Webhook
  - name: node.tir-webhooks.cluster.local
    clientConfig:
      service:
        name: channelog-service
        namespace: tir-webhooks
        path: /node
      caBundle: REDACTED
    rules:
      - operations: ["CREATE", "DELETE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["nodes"]
        scope: "Cluster"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
  # Pod Node Binding Webhook
  - name: pod-binding.tir-webhooks.cluster.local
    clientConfig:
      service:
        name: channelog-service
        namespace: tir-webhooks
        path: /binding
      caBundle: REDACTED
    matchConditions:
      - name: customer-namespace
        expression: 'request.namespace.matches("^p-[0-9]+$")'
    rules:
      - operations: ["*"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods/binding"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
  # Pod Status Webhook
  - name: pod-status.tir-webhooks.cluster.local
    clientConfig:
      service:
        name: channelog-service
        namespace: tir-webhooks
        path: /status
      caBundle: REDACTED
    matchConditions:
      - name: customer-namespace
        expression: 'request.namespace.matches("^p-[0-9]+$")'
    rules:
      - operations: ["UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods/status"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
  # Pod Delete Webhook
  - name: pod-delete.tir-webhooks.cluster.local
    clientConfig:
      service:
        name: channelog-service
        namespace: tir-webhooks
        path: /delete
      caBundle: REDACTED
    matchConditions:
      - name: customer-namespace
        expression: 'request.namespace.matches("^p-[0-9]+$")'
    rules:
      - operations: ["DELETE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
  # Keda Webhook
  - name: keda.tir-webhooks.cluster.local
    clientConfig:
      service:
        name: channelog-service
        namespace: tir-webhooks
        path: /keda
      caBundle: REDACTED
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["deployments", "deployments/scale", "deployments/status"]
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: keda
    objectSelector:
      matchLabels:
        app.kubernetes.io/component: scaler
        app.kubernetes.io/instance: http-add-on
        app.kubernetes.io/part-of: keda-add-ons-http
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
  # Workflow General Webhook
  - name: workflow-normal.tir-webhooks.cluster.local
    clientConfig:
      service:
        name: channelog-service
        namespace: tir-webhooks
        path: /workflow
      caBundle: REDACTED
    rules:
      - apiGroups: ["argoproj.io"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        apiVersions: ["v1alpha1"]
        resources: ["workflows", "workflows/status"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
  # Inference HPA Create/Delete Webhook
  - name: hpa.tir-webhooks.cluster.local
    clientConfig:
      service:
        name: channelog-service
        namespace: tir-webhooks
        path: /inference-hpa
      caBundle: REDACTED
    matchConditions:
      - name: customer-namespace
        expression: 'request.namespace.matches("^p-[0-9]+$")'
    rules:
      - operations: ["CREATE", "DELETE"]
        apiGroups: ["autoscaling"]
        apiVersions: ["v2"]
        resources: ["horizontalpodautoscalers"]
        scope: Namespaced
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
  # Inference HPA Update Webhook
  - name: hpa-status.tir-webhooks.cluster.local
    clientConfig:
      service:
        name: channelog-service
        namespace: tir-webhooks
        path: /inference-hpa
      caBundle: REDACTED
    matchConditions:
      - name: customer-namespace
        expression: 'request.namespace.matches("^p-[0-9]+$")'
    rules:
      - operations: ["UPDATE"]
        apiGroups: ["autoscaling"]
        apiVersions: ["v2"]
        resources: ["horizontalpodautoscalers/status"]
        scope: Namespaced
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
