apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: all-resources-namespaced-channelog-webhook
webhooks:
  - name: spec-sync-ns.yourdomain.com
    clientConfig:
      service:
        name: channelog-service
        namespace: channelog
        path: "/validate"
      # provide the CA bundle that signed your webhook TLS cert here
      caBundle: REDACTED
    matchConditions:
    - name: exclude-p-and-multi
      # only match when ns does NOT start with "p-<digits>" AND does NOT start with "multi-"
      expression: "!(request.namespace.matches('^p-[0-9]+$') || request.namespace.matches('^multi-.*'))"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]        # all root (non-subresource) resources
        scope: Namespaced       # only namespaced objects
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: all-resources-cluster-channelog-webhook
webhooks:
  - name: spec-sync-cluster.yourdomain.com
    clientConfig:
      service:
        name: channelog-service
        namespace: channelog
        path: "/validate"
      caBundle: REDACTED
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]        # all root (non-subresource) resources
        scope: Cluster          # only cluster-scoped objects
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
