apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: channelog-certs
  namespace: channelog
data:
  tls.crt: REDACTED
  tls.key: REDACTED
stringData:
  # Git configuration
  GIT_REPO: "<git_repository_url>"
  GIT_BRANCH: "<git_branch>"
  USERNAME: "<git_username>"
  USER_EMAIL: "<git_user_email>"
  GIT_TOKEN: "<git_token>"
  # Note: SYSTEM_PROMPT and USER_MESSAGE_TEMPLATE are loaded from configmap in deployment.yaml
  # OpenAI configuration
  OPENAI_API_URL: "https://api.openai.com/v1"
  OPENAI_MODEL: "gpt-4"
  OPENAI_API_KEY: ""