apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: channelog-certs
  namespace: tir-webhooks
data:
  tls.crt: REDACTED
  tls.key: REDACTED
stringData:
  DEFAULT_RABBITMQ_QUEUE: tir_webhooks
  RABBITMQ_URL: REDACTED
  LOCATION: Delhi